### ISSUE TITLE
Add support for copyright header in CSS

### ISSUE THREAD

**Issue by AndrewJByrne** [martellaj/license-injector#5]
Hi Joe, thanks for supporting the main types source files. I am sure the list will grow as more folks start using. One that hit me today was CSS. I only add the header if I have modified or created the file, but worth adding.

**Comment by martellaj** [comment]
Definitely an oversight by me if Code exposes that file type. I'll give it a look tomorrow. Thank you for the feedback!

**Comment by martellaj** [comment]
It's the very first language that gets returned. :dancer: Making the update now.

![capture](https://cloud.githubusercontent.com/assets/1019478/11691038/2693e424-9e4e-11e5-9d69-9170b45809f7.PNG)
